channels:
  - conda-forge
  - defaults
dependencies:
  - radiant-mlhub >=0.1.3,<1.0.0
  - rasterio >=1.2,<2
  - fiona
  - shapely
  - geopandas
  - arrow
  - boto3
  - pyproj
  - keras==2.4.3
  - tensorflow==2.4.1
  - tensorflow-hub
  - seaborn
  - scikit-learn
  - pandas
  - numpy
  - matplotlib
  - jupyter
